services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shopflow-sql
    platform: linux/amd64
    environment:
      SA_PASSWORD: "ShopFlow_Dev123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "ShopFlow_Dev123!", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shopflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: shopflow
      RABBITMQ_DEFAULT_PASS: shopflow123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlserver-data:
